spring:
  application:
    name: trading-platform
  profiles:
    active: dev

  datasource:
    url: jdbc:mysql://localhost:3306/trading_dev?createDatabaseIfNotExist=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      database: 0
      timeout: 10000ms

  mail:
    host: live.smtp.mailtrap.io
    port: 587
    username: ${MAILTRAP_USERNAME:demo}
    password: ${MAILTRAP_PASSWORD:demo}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

#  kafka:
#    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
##    ${KAFKA_BOOTSTRAP_SERVERS}
#    properties:
#      auto.create.topics.enable: false
#      allow.auto.create.topics: false
#    consumer:
#      group-id: trading-platform
#      auto-offset-reset: earliest
#      properties:
#        session.timeout.ms: 45000
#        request.timeout.ms: 60000
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#    producer:
#      retries: 10
#      properties:
#        retry.backoff.ms: 1000
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer

trading:
  jwt:
    secret: mySecretKeyForJWTTokenGeneration123456789
    expiration: 86400000

  market-data:
    alpha-vantage:
      api-key: ${ALPHA_VANTAGE_KEY:demo}
      base-url: https://www.alphavantage.co
  kite:
    api-key: ${KITE_API_KEY:key}
    base-url: https://api.kite.trade
  notifications:
    email:
      provider: mailtrap
      from: "noreply@tradingapp.com"

    sms:
      provider: log # Options: log, twilio, jasmin
      from: TradingApp

logging:
  config: classpath:logback-trading.xml
  level:
    com.thousif.trading: DEBUG
    org.springframework.data.redis: DEBUG
    com.fasterxml.jackson: DEBUG